# This is a basic workflow to help you get started with Actions

name: Action Invokation

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Pattern Copy
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repo
      - id: foo
        name: pattern copy
        uses: ./.github/actions/pattern_copy
        with:
          github_token: ${{ secrets.GITHUBACTIONSTOKEN }}
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash